version: '3.4'

services:
  consul:
    ports:
    - "8500:8500"  
  gateway-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ServiceConfig__serviceDiscoveryAddress=http://consul:8500
      - ServiceConfig__serviceAddress=http://gateway-api:8080
      - ServiceConfig__serviceName=gateway
    ports:
      - "8080"

  catalogs-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ServiceConfig__serviceDiscoveryAddress=http://consul:8500
      - ServiceConfig__serviceAddress=http://catalogs-api:8080
      - ServiceConfig__serviceName=catalogs
    deploy:
      replicas: 3
    ports:
      - "8080"

  deliveries-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ServiceConfig__serviceDiscoveryAddress=http://consul:8500
      - ServiceConfig__serviceAddress=http://deliveries-api:8080
      - ServiceConfig__serviceName=deliveries
    deploy:
      replicas: 3
    ports:
      - "8080"

  orders-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ServiceConfig__serviceDiscoveryAddress=http://consul:8500
      - ServiceConfig__serviceAddress=http://orders-api:8080
      - ServiceConfig__serviceName=orders
    deploy:
      replicas: 3
    ports:
      - "8080"

  payments-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ServiceConfig__serviceDiscoveryAddress=http://consul:8500
      - ServiceConfig__serviceAddress=http://payments-api:8080
      - ServiceConfig__serviceName=payments
    deploy:
      replicas: 3
    ports:
      - "8080"

  stock-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ServiceConfig__serviceDiscoveryAddress=http://consul:8500
      - ServiceConfig__serviceAddress=http://stock-api:8080
      - ServiceConfig__serviceName=stock
    deploy:
      replicas: 3
    ports:
      - "8080"